name: binander
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.5
  crypto: ^3.0.2
  flutter_secure_storage: ^8.0.0
  auto_route: ^6.1.0
  go_router: ^6.5.6
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0
  hooks_riverpod: ^2.3.4
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.0.4
  json_annotation: ^4.8.0
  rxdart: ^0.27.7
  uuid: ^3.0.7
  diox: ^5.0.0
  mockito: ^5.4.0
  clock: ^1.1.1
  intl: ^0.17.0
  path_provider: ^2.0.14
  # flutter_adaptive_scaffold: ^0.1.0
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
  #   sdk: flutter    
  test: ^1.19.5
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  mocktail: ^0.3.0
  riverpod_generator: ^2.1.6
  custom_lint: ^0.3.3
  riverpod_lint: ^1.2.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  fake_async: ^1.3.1
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
