name: binander
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.1.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  go_router: ^12.1.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  uuid: ^4.2.1
  diox: ^5.0.0
  clock: ^1.1.1
  intl: ^0.18.1
  path_provider: ^2.1.1
  # flutter_adaptive_scaffold: ^0.1.0
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
  #   sdk: flutter    
  test: ^1.24.3
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  mocktail: ^1.0.1
  riverpod_generator: ^2.3.2
  # custom_lint: ^0.4.0
  riverpod_lint: ^2.1.1
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  fake_async: ^1.3.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
