// ignore_for_file: constant_identifier_names

part of api;

enum SymbolFilterTypes {
  PRICE_FILTER,
  PERCENT_PRICE,
  PERCENT_PRICE_BY_SIDE,
  LOT_SIZE,
  MIN_NOTIONAL,
  ICEBERG_PARTS,
  MARKET_LOT_SIZE,
  MAX_NUM_ORDERS,
  MAX_NUM_ALGO_ORDERS,
  MAX_NUM_ICEBERG_ORDERS,
  MAX_POSITION,
  TRAILING_DELTA,
}
